#!/usr/bin/env python3
"""
build-subset.py - regenerate the self-hosted Tabler icon subset.

The full Tabler webfont is ~800KB and holds 5,300+ icons; the site uses under
200. This keeps only the glyphs the built site actually references.

Run after adding a new icon (the build will tell you, see check-icons.js):

    npm run build            # so _site reflects the new markup
    python3 tools/icons/build-subset.py

Needs fonttools and brotli (pip install fonttools brotli). The Netlify build
does NOT run this; the generated font and CSS are committed.

Icons are scanned from the built HTML and JS rather than the templates, so
names that come from data (navIcon frontmatter, arrays in templates) are
included. The site renders icons by codepoint (content:"\\eXXX"), never by
ligature, so the layout tables are dropped; keeping them breaks the subsetter.
"""
import glob
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.request

VERSION = "3.4.0"
CDN = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}/dist"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SITE = os.path.join(ROOT, "_site")
FONT_OUT = os.path.join(ROOT, "src/assets/fonts/tabler-icons-subset.woff2")
CSS_OUT = os.path.join(ROOT, "src/assets/css/tabler-icons-subset.css")


def fetch(url, path):
    if not os.path.exists(path):
        urllib.request.urlretrieve(url, path)
    return path


def main():
    if not os.path.isdir(SITE):
        sys.exit("run `npm run build` first; this reads the built site")

    tmp = os.path.join(tempfile.gettempdir(), f"tabler-{VERSION}")
    os.makedirs(tmp, exist_ok=True)
    css = open(fetch(f"{CDN}/tabler-icons.min.css", os.path.join(tmp, "t.css")), encoding="utf8").read()
    font = fetch(f"{CDN}/fonts/tabler-icons.woff2", os.path.join(tmp, "t.woff2"))

    defined = dict(re.findall(r'\.ti-([a-z0-9-]+):before\{content:"\\([0-9a-f]+)"\}', css))

    used = set()
    files = glob.glob(SITE + "/**/*.html", recursive=True) + glob.glob(SITE + "/assets/js/*.js")
    for f in files:
        for name in re.findall(r"\bti-([a-z0-9-]+)", open(f, encoding="utf8", errors="ignore").read()):
            if name in defined:
                used.add(name)
    used = sorted(used)

    unicodes = ",".join("U+" + defined[n].upper() for n in used)
    os.makedirs(os.path.dirname(FONT_OUT), exist_ok=True)
    subprocess.run([
        sys.executable, "-m", "fontTools.subset", font,
        f"--unicodes={unicodes}", "--flavor=woff2", f"--output-file={FONT_OUT}",
        "--layout-features=", "--drop-tables+=GSUB,GPOS", "--no-hinting",
    ], check=True)

    rules = "".join(f'.ti-{n}:before{{content:"\\{defined[n]}"}}' for n in used)
    with open(CSS_OUT, "w", encoding="utf8") as fh:
        fh.write(
            f"/* Tabler Icons {VERSION} (MIT, https://tabler.io), subset to the {len(used)} icons\n"
            "   this site uses. Generated by tools/icons/build-subset.py; do not edit by hand. */\n"
            '@font-face{font-family:"tabler-icons";font-style:normal;font-weight:400;font-display:block;'
            'src:url("/assets/fonts/tabler-icons-subset.woff2") format("woff2")}'
            '.ti{font-family:"tabler-icons"!important;speak:none;font-style:normal;font-weight:normal;'
            "font-variant:normal;text-transform:none;line-height:1;-webkit-font-smoothing:antialiased;"
            "-moz-osx-font-smoothing:grayscale}\n" + rules + "\n"
        )
    print(f"{len(used)} icons -> {os.path.getsize(FONT_OUT)/1024:.1f} KB font, "
          f"{os.path.getsize(CSS_OUT)/1024:.1f} KB css")


if __name__ == "__main__":
    main()
