[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = "/platform/121-commerce/"
  to = "/platform/cxp/"
  status = 301

[[redirects]]
  from = "/solutions/"
  to = "/platform/tcs/"
  status = 301

[[redirects]]
  from = "/platform/pxp/"
  to = "/features/product-data/"
  status = 301

[[redirects]]
  from = "/platform/cxp/"
  to = "/features/customer-data/"
  status = 301

[[redirects]]
  from = "/platform/tap/"
  to = "/features/access-identity/"
  status = 301

[[redirects]]
  from = "/platform/teammate/"
  to = "/features/access-identity/"
  status = 301

[[redirects]]
  from = "/platform/lms/"
  to = "/features/training/"
  status = 301

[[redirects]]
  from = "/platform/tcs/"
  to = "/platform/mobile-pos/"
  status = 301

[[redirects]]
  from = "/platform/shopper-services/"
  to = "/platform/mobile-pos/#shopper-display"
  status = 301

[[redirects]]
  from = "/partners/"
  to = "https://partners.teamworkcommerce.com/integrations"
  status = 301
  force = true
